---
title: "genepop analysis"
output: html_document
date: "2026-03-02"
---

```{r}
library(dplyr)
library(adegenet)
library(spdep)
library(adespatial)
```

```{r}
genepop <- read.genepop("guttata101_r0.5.populations.snps.gen")
```

```{r}
X <- tab(genepop, NA.method = "mean")   # allele counts, imputing missing data
pca2 <- dudi.pca(X, scannf = FALSE, nf = 2)

scores2 <- as.data.frame(pca2$li)
scores2$pop <- pop(genepop)
```

```{r}
ggplot(scores2, aes(Axis1, Axis2, color = pop)) +
  geom_point(size = 3) +
  theme_classic()

limit <-  50
ggplot(scores2, aes(Axis1, Axis2, color = pop)) +
  geom_point(size = 3) +
  scale_y_continuous(limits = c(-limit, limit)) +
  scale_x_continuous(limits = c(-limit, limit)) +
  theme_classic()

limit <-  10
ggplot(scores2, aes(Axis1, Axis2, color = pop)) +
  geom_point(size = 3) +
  scale_y_continuous(limits = c(-limit, limit)) +
  scale_x_continuous(limits = c(-limit, limit)) +
  theme_classic()

limit <-  1
ggplot(scores2, aes(Axis1, Axis2, color = pop)) +
  geom_point(size = 3) +
  scale_y_continuous(limits = c(-limit, limit)) +
  scale_x_continuous(limits = c(-limit, limit)) +
  theme_classic()

limit <-  .1
ggplot(scores2, aes(Axis1, Axis2, color = pop)) +
  geom_point(size = 3) +
  scale_y_continuous(limits = c(-limit, limit)) +
  scale_x_continuous(limits = c(-limit, limit)) +
  theme_classic()

```
